# Generated by Django 4.2.5 on 2023-10-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='current_active',
            field=models.BooleanField(default=False),
        ),
    ]
