# Generated by Django 4.2.5 on 2023-10-11 07:44

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_usertable_current_active"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usertable",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
