# Generated by Django 4.2.5 on 2023-10-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneChat',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_id', models.PositiveIntegerField()),
                ('receiver_id', models.PositiveIntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
