# Generated by Django 4.2.5 on 2023-10-10 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_onechat_sender_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="onechat",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="onechat",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="onechat",
            name="message_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
