# Generated by Django 4.2.5 on 2023-10-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_onechat_is_read_onechat_is_sent_onechat_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='onechat',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
