# Generated by Django 4.2.5 on 2023-10-12 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_group_remove_groupchat_receivers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.group'),
        ),
    ]
