# Generated by Django 4.2.5 on 2023-10-12 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0016_alter_groupchat_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onechat',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='onechat',
            name='sender_id',
            field=models.PositiveIntegerField(),
        ),
    ]
